### PR TITLE
Add which-branch action so tag builds can identify corresponding branch.

### PR DESCRIPTION
**Pull request by nat-goodspeed**
Our github package releases are driven by tag builds. For a tag build, `github.ref_name` is the tag, not the corresponding branch, and the local clone on the runner presents a detached HEAD.

But for some purposes it's important to identify the branch we tagged. `which-branch` looks up the branch corresponding to the specified tag or commit hash.

### CODE REVIEW

**Comment by nat-goodspeed** [comment]
I maintain that the last change requested by flake8 would decrease readability.

**Comment by bennettgoble** [comment]
@nat-goodspeed thanks for the PR. Would it be simpler to call a git operation such as `git branch --contains ${{ github.sha }}` instead of using the REST API?

In case it is a problem, you can also work around the fact that in the context of a pull request `github.sha` references a dynamic merge commit rather than the branch head (https://frontside.com/blog/2020-05-26-github-actions-pull_request/#how-does-pull_request-affect-actionscheckout) like so:

```
env:
  SHA: ${{ github.event.pull_request.head.sha || github.sha }}
```

...however since the builds are triggered by a tag rather than a pull_request event this shouldn't be necessary and you can likely just get away with using `github.sha`.

**Comment by nat-goodspeed** [comment]
I don't know of any way to constrain the output of `git branch --contains` to the exact tip, or to order by closest match. Most of the time, I stipulate, that wouldn't matter. But for instance, the viewer maint V branch was merged into the maint W branch before this last release. As far as I know, `git branch --contains` with the tip of the maint V branch would show both, in either order.

That said, it's susceptible to testing on a runner host. Of course `git branch` only queries the local clone. The fact that a runner typically checks out only the changeset of interest may constrain it to exactly one branch -- or it may not know the branch name at all.

**Comment by bennettgoble** [comment]
@nat-goodspeed you may be helped by the fact that the build is being triggered in the context of a `tag` event. At that point it should be safe to assume that only one branch has the tag --the branch that was just pushed to.

As for `git branch --contains` only querying the local checkout --you're right. It appears that this can be worked around by with the `-r` remote option.

**Comment by nat-goodspeed** [comment]
https://github.com/secondlife/3p-tinygltf/actions/runs/7223386933/job/19682333728#step:3:1

    Run git branch --contains 5d136c310af31e1ed36d267709814897f32b7dcc
    * (HEAD detached at 5d136c3)

**Comment by nat-goodspeed** [comment]
Good call about `-r` though:

https://github.com/secondlife/3p-tinygltf/actions/runs/7226860581/job/19693328184#step:3:1

    Run git branch -r --contains 2e282419db87d3e476023f90c8067ca13b5aa3f7
    origin/actions

**Review by bennettgoble — APPROVED** [review]

**Pull request merged**
